# Generated by Django 5.0.6 on 2024-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Done'),
        ),
    ]
